//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIMS.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillSequence
    {
        public string dtadat { get; set; }
        public short ter_id { get; set; }
        public Nullable<short> seq { get; set; }
        public Nullable<bool> Trng_fg { get; set; }
    }
}
