//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIMS.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public decimal code { get; set; }
        public string name { get; set; }
        public string shortname { get; set; }
        public Nullable<bool> actv_fg { get; set; }
        public Nullable<System.DateTime> dtadat { get; set; }
        public string dtatim { get; set; }
        public string dtausr { get; set; }
        public Nullable<bool> Trng_fg { get; set; }
    }
}
