//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIMS.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormCollection
    {
        public decimal FormId { get; set; }
        public string FormName { get; set; }
        public string FormCap { get; set; }
        public string Descr { get; set; }
        public string FormGrp { get; set; }
        public string status { get; set; }
    }
}
