//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIMS.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invdet
    {
        public decimal vno { get; set; }
        public int srno { get; set; }
        public decimal itm_code { get; set; }
        public Nullable<short> qty { get; set; }
        public Nullable<decimal> rtl_prc { get; set; }
        public Nullable<decimal> amt { get; set; }
        public Nullable<bool> Trng_fg { get; set; }
    }
}
