//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIMS.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invtrn
    {
        public decimal vno { get; set; }
        public short ter_id { get; set; }
        public Nullable<bool> export_fg { get; set; }
        public short tran_type { get; set; }
        public string doc_no { get; set; }
        public System.DateTime rec_dat { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> dtadat { get; set; }
        public string dtatim { get; set; }
        public string dtausr { get; set; }
        public Nullable<bool> Trng_fg { get; set; }
        public Nullable<int> TerminalCode { get; set; }
        public string FileName { get; set; }
    }
}
