//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIMS.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public decimal code { get; set; }
        public string name { get; set; }
        public string shortname { get; set; }
        public Nullable<bool> actv_fg { get; set; }
        public Nullable<decimal> category_id { get; set; }
        public Nullable<decimal> size_id { get; set; }
        public Nullable<decimal> rtl_prc { get; set; }
        public Nullable<decimal> disc_per { get; set; }
        public Nullable<decimal> disc_amt { get; set; }
        public Nullable<System.DateTime> dtadat { get; set; }
        public string dtatim { get; set; }
        public string dtausr { get; set; }
        public Nullable<decimal> unit_id { get; set; }
        public Nullable<short> BillFmt { get; set; }
        public Nullable<bool> Trng_fg { get; set; }
        public Nullable<short> min_qty { get; set; }
        public Nullable<short> max_qty { get; set; }
    }
}
