//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIMS.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerExport
    {
        public decimal Id { get; set; }
        public string TableName { get; set; }
        public string TableType { get; set; }
        public string sWhere { get; set; }
        public Nullable<bool> actv_fg { get; set; }
    }
}
