//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIMS.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerSaltrn
    {
        public string tran_id { get; set; }
        public short ter_id { get; set; }
        public Nullable<bool> export_fg { get; set; }
        public Nullable<decimal> paid_amt { get; set; }
        public Nullable<decimal> change_amt { get; set; }
        public Nullable<System.DateTime> dtadat { get; set; }
        public string dtatim { get; set; }
        public string dtausr { get; set; }
        public Nullable<bool> Canceled { get; set; }
        public Nullable<short> Event_id { get; set; }
        public Nullable<bool> Trng_fg { get; set; }
    }
}
