//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIMS.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMast
    {
        public decimal Uid { get; set; }
        public string Uname { get; set; }
        public string pwd { get; set; }
        public Nullable<int> Level { get; set; }
        public string status { get; set; }
        public Nullable<bool> Trng_fg { get; set; }
    }
}
