//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIMS.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRight
    {
        public decimal Uid { get; set; }
        public decimal FormId { get; set; }
        public string add { get; set; }
        public string del { get; set; }
        public string edit { get; set; }
        public string print { get; set; }
        public string Nevigate { get; set; }
        public string report { get; set; }
        public string status { get; set; }
    }
}
